// CREATE NEW PROJECT HTML AND GET NAME
// STORE ARRAY HERE OR IN INDEX?

// WHEN CALLED SHOULD TAKE NAME INPUT THEN BUILD AND RENDER NEW PROJECT WITH APPROPRIATE HEADER NAME, COLUMN TITLES, AND SINGLE DUMMY INPUT
